apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: voting-system
data:
  AUTH_PORT: "3001"
  ELECTION_PORT: "3002"
  VOTE_PORT: "3003"
  REDIS_URL: "redis://redis-service:6379"
  RUST_LOG: "info,tower_http=debug"
